name: news_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.7.9
  - pip
  - tensorflow = 2.3.0
  - pip:
    - nltk==3.5
    - numpy==1.18.0
    - pandas==1.2.3
    - fastapi==0.63.0
    - uvicorn[standard]
    - sklearn==0.0



