name: news_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.7.9
  - pip
  - tensorflow = 2.3.0
  - pip:
    - nltk
    - numpy==1.18.0
    - pandas
    - fastapi
    - uvicorn[standard]
    - sklearn



